Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -95,18 +95,20 @@ jobs:
             docker.io/${{ env.IMAGE_REGISTRY_NAMESPACE }}/${{ env.IMAGE_REPOSITORY }}:${{ steps.vars.outputs.image_tag }}
           target: JAVA_BASE_IMAGE
 
-      - name: Test Built Image
+      - name: Test Pushed Image
+        if: github.ref_name == 'master'
         run: |
+          IMAGE=docker.io/${{ env.IMAGE_REGISTRY_NAMESPACE }}/${{ env.IMAGE_REPOSITORY }}:${{ steps.vars.outputs.image_tag }}
           echo -n "Checking for java version: "
-          docker run local/${{ env.IMAGE_REPOSITORY }}:ci java -version 2>&1 \
-          | grep -i 'version \"${{ matrix.java_major }}\.'
+          docker run --rm $IMAGE java -version 2>&1 | grep -i "version \"${{ matrix.java_major }}\."
           echo -n "Checking shell environment: "
-          BASH_LOGIN="$(docker run local/${{ env.IMAGE_REPOSITORY }}:ci /bin/bash 2>&1 > /dev/null || true)"
+          BASH_LOGIN="$(docker run --rm $IMAGE /bin/bash 2>&1 > /dev/null || true)"
           if [ -z "$BASH_LOGIN" ]; then
             echo ok
             echo -n "Image architecture: "
-            docker image inspect local/alfresco-base-java:ci --format '{{.Architecture}}'
-          else echo 'bash reported an error'
+            docker image inspect $IMAGE --format '{{.Architecture}}'
+          else
+            echo 'bash reported an error'
             echo $BASH_LOGIN
             exit 7
           fi
